Bug 1883749  Use memmove instead of strncpy to avoid warning. r=benc
gcc-12 and later gives this warning.
To make the compile-time warnings terse, use memmove.

error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 3 equals destination size [-Werror=stringop-truncation]
  809 |         strncpy(mLastBlockChars, readBuf + readCount - 3, 3);
      |                ^

Differential Revision: https://phabricator.services.mozilla.com/D203669